#162163132 Users should be able to Login via Google or Facebook
andela/ah-frontend-zeus pull request #26
Opened 2019-01-18 06:00 UTC by alexkayabula

## What does this PR do?
- The PR ensures that users can log in using their favourite social media platform.
### Description of task to be completed?
- Users should be able to Login via Google or Facebook.
### How should this be manually tested?
- Clone the repository.
- Install the dependencies using `yarn install`.
- Start the application using `yarn start`.
- Click the respective buttons to login via Facebook or Google.
<img width="1234" alt="screen shot 2019-01-18 at 07 47 15" src="https://user-images.githubusercontent.com/31479458/51367990-44374900-1afe-11e9-9fdc-1abd476a5554.png">

 ## Login with Facebook.
<img width="469" alt="screen shot 2019-01-18 at 07 50 10" src="https://user-images.githubusercontent.com/31479458/51368024-7648ab00-1afe-11e9-83b0-51f453f990d6.png">

## Login with Google.
<img width="517" alt="screen shot 2019-01-18 at 07 48 08" src="https://user-images.githubusercontent.com/31479458/51368041-86608a80-1afe-11e9-8252-b63d71d85642.png">

### What are the relevant pivotal tracker stories?
[#162163132](https://www.pivotaltracker.com/story/show/162163132)

2019-01-23 15:11 UTC, sekayasin approved these changes
LGTM

2019-01-23 15:17 UTC, barema4 reviewed
Nice work, could you please add  `A user should have facebook or google account to signup` on how this task is manually tested

2019-01-23 16:04 UTC, alexkayabula commented
> Nice work, could you please add `A user should have facebook or google account to signup` on how this task is manually tested

I think you meant "sign in". Let me work on that.

2019-01-23 17:23 UTC, ekumamait approved these changes
Nice work @alexkayabula looks good to merge.

2019-01-24 05:59 UTC, ongebo approved these changes

2019-01-24 08:37 UTC, RrNn requested changes
Move the `registerReducer.test.js` file to the `__tests__` directory

2019-01-24 09:06 UTC, alexkayabula commented
> Move the `registerReducer.test.js` file to the `__tests__` directory

OK .... Let me do that

2019-01-24 14:14 UTC, RrNn requested changes
Add new lines at the end of files.

2019-01-24 14:14 UTC, RrNn commented on src/store/index.js
> +export default store;
Add a new black line here

2019-01-24 14:14 UTC, RrNn commented on src/actions/actionTypes.js
> +export default actionTypes;
Add a new blank line here

2019-01-24 14:19 UTC, alexkayabula commented on src/store/index.js
> +export default store;
I have made the changes.

2019-01-24 14:20 UTC, alexkayabula commented on src/actions/actionTypes.js
> +export default actionTypes;
I have made the changes

2019-01-24 14:29 UTC, RrNn approved these changes

2019-01-24 14:29 UTC, merged