#162163137 Pagination support for articles
andela/ah-frontend-zeus pull request #42
Opened 2019-01-25 07:53 UTC by lindseyme

### What does this PR do?
This Pull Request adds pagination support to articles.

#### Description of Task to be completed?
Add pagination to our articles to make article traversal easier.

#### How should this be manually tested?
- Clone the repository then checkout to the branch `ft-pagination-162163137`.
- Install the required dependencies.
     - yarn 
- Start the server.
     - yarn start
- Run the project in the browser.
- Click on the login button on the interface and fill in the details. 
- The articles are displayed on pages and a maximum of 10 per page.

#### What are the relevant pivotal tracker stories?
[#162163137](https://www.pivotaltracker.com/story/show/162163137)

2019-01-29 15:45 UTC, sekayasin commented on src/components/articles/ArticlesFeed.js
> +    this.props.getArticles('https://zeus-staging.herokuapp.com/api/articles/');
Bravo, just change this to our environment variable

2019-01-29 15:47 UTC, ekumamait approved these changes
LQTM

2019-01-29 16:02 UTC, lindseyme commented on src/components/articles/ArticlesFeed.js
> +    this.props.getArticles('https://zeus-staging.herokuapp.com/api/articles/');
Okay, I have done that

2019-01-29 16:03 UTC, ongebo approved these changes
LGTM

2019-01-29 16:51 UTC, barema4 approved these changes
Nice work

2019-01-30 08:19 UTC, RrNn requested changes
@lindseyme , the `Next` button should be on the right.
<img width="239" alt="screen shot 2019-01-30 at 11 17 53" src="https://user-images.githubusercontent.com/30738053/51967633-e4875900-2480-11e9-837f-7d80fd97ebe7.png">

2019-01-30 08:24 UTC, lindseyme commented
> @lindseyme , the `Next` button should be on the right.
> <img alt="screen shot 2019-01-30 at 11 17 53" width="239" src="https://user-images.githubusercontent.com/30738053/51967633-e4875900-2480-11e9-837f-7d80fd97ebe7.png">

2019-01-30 11:26 UTC, merged