#162163148 Users should be able to report an article
andela/ah-frontend-zeus pull request #49
Opened 2019-01-31 02:49 UTC by alexkayabula

### What does this PR do?
This Pull Request enables users to report articles that violate Authors Haven terms and agreements.

#### Description of Task to be completed?
When a user visits the Authors Haven application, he/she should be able to report any articles they find to violate Authors Haven terms and agreements. 

#### How should this be manually tested?
- Clone the repository then checkout to the branch `ft-report-article-162163148 `.
- Install the required dependencies.
     - yarn 
- Start the server.
     - yarn start
- Run the project in the browser.
- Access the report article option to report any article.
<img width="6" alt="screen shot 2019-01-31 at 05 28 18" src="https://user-images.githubusercontent.com/31479458/52027221-a4c17f80-251b-11e9-914c-91dfe0c93b22.png">
<img width="979" alt="screen shot 2019-01-31 at 05 28 52" src="https://user-images.githubusercontent.com/31479458/52027226-a8550680-251b-11e9-969c-1753d812544e.png">
<img width="973" alt="screen shot 2019-01-31 at 05 29 44" src="https://user-images.githubusercontent.com/31479458/52027227-aa1eca00-251b-11e9-8a50-ba56e11a3d69.png">

#### What are the relevant pivotal tracker stories?
[#162163148](https://www.pivotaltracker.com/story/show/162163148)

2019-01-31 17:22 UTC, ongebo approved these changes
Looks good to me.

2019-01-31 17:26 UTC, sekayasin approved these changes
LGTM

2019-01-31 17:42 UTC, mulondo approved these changes

2019-01-31 17:56 UTC, RrNn requested changes

2019-01-31 17:56 UTC, RrNn commented on src/actions/ArticlesActions.js
> +      console.log(response)
Remove this `console.log`

2019-01-31 17:56 UTC, RrNn commented on src/actions/socialAction.js
> +        console.log(dispatch);
Remove this `console.log`

2019-01-31 17:56 UTC, RrNn commented on src/actions/socialAction.js
> +        console.log(data.user.username);
Remove these 2 `console.logs`

2019-02-01 06:20 UTC, alexkayabula commented on src/actions/ArticlesActions.js
> +      console.log(response)
They have been removed.

2019-02-01 06:20 UTC, alexkayabula commented on src/actions/socialAction.js
> +        console.log(data.user.username);
It has been removed

2019-02-01 06:28 UTC, merged